### ISSUE TITLE
error getting XSTS token + more 

### ISSUE THREAD

**Issue by GeyserConnect-Asia** [rtm516/MCXboxBroadcast#10]
2023-01-05 18:29:51.110 [ERROR] Failed to get XSTS authentication token
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "Identity" (class com.rtm516.mcxboxbroadcast.core.models.GenericAuthenticationResponse), not marked as ignorable (4 known properties: "IssueInstant", "NotAfter", "Token", "DisplayClaims"])
 at [Source: (String)"{"Identity":"0","XErr":2148916233,"Message":"","Redirect":"https://start.ui.xboxlive.com/CreateAccount"}"; line: 1, column: 14] (through reference chain: com.rtm516.mcxboxbroadcast.core.models.GenericAuthenticationResponse["Identity"])
        at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
        at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:1127)
        at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1989)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1700)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1678)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:319)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:176)
        at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4674)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3629)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3597)
        at com.rtm516.mcxboxbroadcast.core.XboxTokenManager.getXSTSToken(XboxTokenManager.java:302)
        at com.rtm516.mcxboxbroadcast.core.SessionManager.getXboxToken(SessionManager.java:108)
        at com.rtm516.mcxboxbroadcast.core.SessionManager.createSession(SessionManager.java:140)
        at com.rtm516.mcxboxbroadcast.core.SessionManager.createSession(SessionManager.java:129)
        at com.rtm516.mcxboxbroadcast.bootstrap.standalone.StandaloneMain.main(StandaloneMain.java:82)
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "com.rtm516.mcxboxbroadcast.core.models.XboxTokenInfo.tokenHeader()" because "tokenInfo" is null
        at com.rtm516.mcxboxbroadcast.core.SessionManager.createSession(SessionManager.java:141)
        at com.rtm516.mcxboxbroadcast.core.SessionManager.createSession(SessionManager.java:129)
        at com.rtm516.mcxboxbroadcast.bootstrap.standalone.StandaloneMain.main(StandaloneMain.java:82)

**Comment by GeyserConnect-Asia** [comment]
https://mclo.gs/coQnQh7

**Comment by GeyserConnect-Asia** [comment]
both the same

**Comment by JulianICE08935** [comment]
OK

Gesendet von Outlook für Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by JulianICE08935** [comment]
it works on my phone

**Comment by JulianICE08935** [comment]
this tool runs very well with the Termux app on my phone

**Comment by JulianICE08935** [comment]
and I have no faults

**Comment by rtm516** [comment]
Not had any other reports of this so closing
Please make sure your account isn't a restricted account
