### ISSUE TITLE
I can't find my Xbox link code 

### ISSUE THREAD

**Issue by harugames4407** [rtm516/MCXboxBroadcast#104]
When I first started the game, I tried to enter my Xbox Live link code, but the code didn't appear.

Can you fix this somehow? (Sorry if that's not possible)

**Comment by rtm516** [comment]
Not entirely sure what you mean. Do you mean when you start the tool it doesn't show the code to login to the account you want to use? If so please share logs from the tool

**Comment by harugames4407** [comment]
This is the first time it was started and the log 
https://github.com/user-attachments/assets/4e498e91-a29c-40e4-b1fc-0743572740b5

log
_[22:04:24.435 main/INFO] Starting MCXboxBroadcast Standalone build 37 (git-master-d802714)
[22:04:26.672 main/ERROR] [Primary Session] Failed to ping server
java.util.concurrent.ExecutionException: java.util.concurrent.TimeoutException
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
	at com.rtm516.mcxboxbroadcast.bootstrap.standalone.StandaloneMain.updateSessionInfo(StandaloneMain.java:117) [server.jar:?]
	at com.rtm516.mcxboxbroadcast.bootstrap.standalone.StandaloneMain.main(StandaloneMain.java:71) [server.jar:?]
Caused by: java.util.concurrent.TimeoutException
	at com.nukkitx.network.raknet.RakNetClient.onTick(RakNetClient.java:121) ~[server.jar:?]
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) ~[server.jar:?]
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:159) ~[server.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[server.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[server.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[server.jar:?]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:406) ~[server.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[server.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[server.jar:?]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[22:04:26.692 main/INFO] [Primary Session] Starting SessionManager...
[22:04:26.702 main/INFO] [Auth] Getting device code for MSA login...
[22:04:42.766 main/ERROR] [Primary Session] Failed to get/refresh auth token
java.net.http.HttpConnectTimeoutException: HTTP connect timed out
	at jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:945) ~[java.net.http:?]
	at jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:133) ~[java.net.http:?]
	at net.lenni0451.commons.httpclient.executor.HttpClientExecutor.execute(HttpClientExecutor.java:48) ~[server.jar:?]
	at net.lenni0451.commons.httpclient.HttpClient.execute(HttpClient.java:232) ~[server.jar:?]
	at net.lenni0451.commons.httpclient.HttpClient.execute(HttpClient.java:213) ~[server.jar:?]
	at net.raphimc.minecraftauth.step.msa.StepMsaDeviceCode.applyStep(StepMsaDeviceCode.java:60) ~[server.jar:?]
	at net.raphimc.minecraftauth.step.msa.StepMsaDeviceCode.applyStep(StepMsaDeviceCode.java:37) ~[server.jar:?]
	at net.raphimc.minecraftauth.step.AbstractStep.getFromInput(AbstractStep.java:80) ~[server.jar:?]
	at net.raphimc.minecraftauth.step.AbstractStep.getFromInput(AbstractStep.java:80) ~[server.jar:?]
	at net.raphimc.minecraftauth.step.AbstractStep.getFromInput(AbstractStep.java:80) ~[server.jar:?]
	at net.raphimc.minecraftauth.step.msa.StepMsaToken.getFromInput(StepMsaToken.java:68) ~[server.jar:?]
	at net.raphimc.minecraftauth.step.msa.StepMsaToken.getFromInput(StepMsaToken.java:36) ~[server.jar:?]
	at net.raphimc.minecraftauth.step.BiMergeStep.getFromInput(BiMergeStep.java:53) ~[server.jar:?]
	at net.raphimc.minecraftauth.step.BiMergeStep.getFromInput(BiMergeStep.java:23) ~[server.jar:?]
	at net.raphimc.minecraftauth.step.AbstractStep.getFromInput(AbstractStep.java:80) ~[server.jar:?]
	at net.raphimc.minecraftauth.step.AbstractStep.getFromInput(AbstractStep.java:66) ~[server.jar:?]
	at com.rtm516.mcxboxbroadcast.core.AuthManager.initialise(AuthManager.java:74) [server.jar:?]
	at com.rtm516.mcxboxbroadcast.core.AuthManager.getXboxToken(AuthManager.java:99) [server.jar:?]
	at com.rtm516.mcxboxbroadcast.core.SessionManagerCore.getXboxToken(SessionManagerCore.java:109) [server.jar:?]
	at com.rtm516.mcxboxbroadcast.core.SessionManagerCore.init(SessionManagerCore.java:126) [server.jar:?]
	at com.rtm516.mcxboxbroadcast.core.SessionManager.init(SessionManager.java:84) [server.jar:?]
	at com.rtm516.mcxboxbroadcast.bootstrap.standalone.StandaloneMain.createSession(StandaloneMain.java:92) [server.jar:?]
	at com.rtm516.mcxboxbroadcast.bootstrap.standalone.StandaloneMain.main(StandaloneMain.java:73) [server.jar:?]
Caused by: java.net.http.HttpConnectTimeoutException: HTTP connect timed out
	at jdk.internal.net.http.MultiExchange.toTimeoutException(MultiExchange.java:585) ~[java.net.http:?]
	at jdk.internal.net.http.MultiExchange.getExceptionalCF(MultiExchange.java:532) ~[java.net.http:?]
	at jdk.internal.net.http.MultiExchange.lambda$responseAsyncImpl$7(MultiExchange.java:452) ~[java.net.http:?]
	at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniHandleStage(CompletableFuture.java:950) ~[?:?]
	at java.util.concurrent.CompletableFuture.handle(CompletableFuture.java:2372) ~[?:?]
	at jdk.internal.net.http.MultiExchange.responseAsyncImpl(MultiExchange.java:444) ~[java.net.http:?]
	at jdk.internal.net.http.MultiExchange.lambda$responseAsync0$2(MultiExchange.java:346) ~[java.net.http:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773) ~[?:?]
	at jdk.internal.net.http.HttpClientImpl$DelegatingExecutor.execute(HttpClientImpl.java:177) ~[java.net.http:?]
	at java.util.concurrent.CompletableFuture.completeAsync(CompletableFuture.java:2719) ~[?:?]
	at jdk.internal.net.http.MultiExchange.responseAsync(MultiExchange.java:299) ~[java.net.http:?]
	at jdk.internal.net.http.HttpClientImpl.sendAsync(HttpClientImpl.java:1047) ~[java.net.http:?]
	at jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:930) ~[java.net.http:?]
	... 22 more
Caused by: java.net.ConnectException: HTTP connect timed out
	at jdk.internal.net.http.MultiExchange.toTimeoutException(MultiExchange.java:586) ~[java.net.http:?]
	at jdk.internal.net.http.MultiExchange.getExceptionalCF(MultiExchange.java:532) ~[java.net.http:?]
	at jdk.internal.net.http.MultiExchange.lambda$responseAsyncImpl$7(MultiExchange.java:452) ~[java.net.http:?]
	at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniHandleStage(CompletableFuture.java:950) ~[?:?]
	at java.util.concurrent.CompletableFuture.handle(CompletableFuture.java:2372) ~[?:?]
	at jdk.internal.net.http.MultiExchange.responseAsyncImpl(MultiExchange.java:444) ~[java.net.http:?]
	at jdk.internal.net.http.MultiExchange.lambda$responseAsync0$2(MultiExchange.java:346) ~[java.net.http:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773) ~[?:?]
	at jdk.internal.net.http.HttpClientImpl$DelegatingExecutor.execute(HttpClientImpl.java:177) ~[java.net.http:?]
	at java.util.concurrent.CompletableFuture.completeAsync(CompletableFuture.java:2719) ~[?:?]
	at jdk.internal.net.http.MultiExchange.responseAsync(MultiExchange.java:299) ~[java.net.http:?]
	at jdk.internal.net.http.HttpClientImpl.sendAsync(HttpClientImpl.java:1047) ~[java.net.http:?]
	at jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:930) ~[java.net.http:?]
	... 22 more_

**Comment by rtm516** [comment]
Looks like the tool can't reach the internet or your bedrock/geyser server. Please check the network settings of the machine it's running on and make sure it can talk straight to the internet
