### ISSUE TITLE
Crash when starting after login

### ISSUE THREAD

**Issue by Ai-Kiwi** [rtm516/MCXboxBroadcast#11]
java -Xms128M -Xmx1024M -jar MCXboxBroadcastStandalone.jar
2023-02-07 04:28:46.981 [INFO] Creating session...
2023-02-07 04:28:47.611 [INFO] To sign in, use a web browser to open the page https://www.microsoft.com/link and enter the code MAJDY9TU to authenticate.
2023-02-07 04:29:12.383 [ERROR] Failed to get XSTS authentication token
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "Identity" (class com.rtm516.mcxboxbroadcast.core.models.GenericAuthenticationResponse), not marked as ignorable (4 known properties: "IssueInstant", "NotAfter", "Token", "DisplayClaims"])
 at [Source: (String)"{"Identity":"0","XErr":2148916233,"Message":"","Redirect":"https://start.ui.xboxlive.com/CreateAccount"}"; line: 1, column: 14] (through reference chain: com.rtm516.mcxboxbroadcast.core.models.GenericAuthenticationResponse["Identity"])
        at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
        at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:1127)
        at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1989)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1700)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1678)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:319)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:176)
        at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4674)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3629)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3597)
        at com.rtm516.mcxboxbroadcast.core.XboxTokenManager.getXSTSToken(XboxTokenManager.java:302)
        at com.rtm516.mcxboxbroadcast.core.SessionManager.getXboxToken(SessionManager.java:108)
        at com.rtm516.mcxboxbroadcast.core.SessionManager.createSession(SessionManager.java:140)
        at com.rtm516.mcxboxbroadcast.core.SessionManager.createSession(SessionManager.java:129)
        at com.rtm516.mcxboxbroadcast.bootstrap.standalone.StandaloneMain.main(StandaloneMain.java:82)
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "com.rtm516.mcxboxbroadcast.core.models.XboxTokenInfo.tokenHeader()" because "tokenInfo" is null
        at com.rtm516.mcxboxbroadcast.core.SessionManager.createSession(SessionManager.java:141)
        at com.rtm516.mcxboxbroadcast.core.SessionManager.createSession(SessionManager.java:129)
        at com.rtm516.mcxboxbroadcast.bootstrap.standalone.StandaloneMain.main(StandaloneMain.java:82)

**Comment by HeadHunterPvP** [comment]
2023-02-07 04:29:12.383 [ERROR] Failed to get XSTS authentication token > Hense they caught you or you don't have minecraft. As a token is needed to run the broadcaster.

**Comment by HeadHunterPvP** [comment]
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "com.rtm516.mcxboxbroadcast.core.models.XboxTokenInfo.tokenHeader()" because "tokenInfo" is null

**Comment by Ai-Kiwi** [comment]
Forgot to mention. I fixed my issue by making a xbox account and then clearing my cache.
