### ISSUE TITLE
Unable to get current friend count com.google.gson.JsonSyntaxException: java.lang.NumberFormatException

### ISSUE THREAD

**Issue by mastachef** [rtm516/MCXboxBroadcast#116]
[22:32:32 ERROR] [Sub-Session playcomplex1] Unable to get current friend count
com.google.gson.JsonSyntaxException: java.lang.NumberFormatException: Expected an int but was 4294967284 at line 1 column 305 path $.availablePeopleSlots
        at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:277) ~[MCXboxBroadcastStandalone.jar:?]
        at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:267) ~[MCXboxBroadcastStandalone.jar:?]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$2.readIntoArray(ReflectiveTypeAdapterFactory.java:253) ~[MCXboxBroadcastStandalone.jar:?]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$RecordAdapter.readField(ReflectiveTypeAdapterFactory.java:638) ~[MCXboxBroadcastStandalone.jar:?]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$RecordAdapter.readField(ReflectiveTypeAdapterFactory.java:567) ~[MCXboxBroadcastStandalone.jar:?]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:516) ~[MCXboxBroadcastStandalone.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1361) ~[MCXboxBroadcastStandalone.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1262) ~[MCXboxBroadcastStandalone.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1171) ~[MCXboxBroadcastStandalone.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1107) ~[MCXboxBroadcastStandalone.jar:?]
        at com.rtm516.mcxboxbroadcast.core.SessionManagerCore.socialSummary(SessionManagerCore.java:391) [MCXboxBroadcastStandalone.jar:?]
        at com.rtm516.mcxboxbroadcast.core.SessionManager.listSessions(SessionManager.java:280) [MCXboxBroadcastStandalone.jar:?]
        at com.rtm516.mcxboxbroadcast.bootstrap.standalone.StandaloneLoggerImpl.runCommand(StandaloneLoggerImpl.java:84) [MCXboxBroadcastStandalone.jar:?]
        at net.minecrell.terminalconsole.SimpleTerminalConsole.processInput(SimpleTerminalConsole.java:87) [MCXboxBroadcastStandalone.jar:?]
        at net.minecrell.terminalconsole.SimpleTerminalConsole.readCommands(SimpleTerminalConsole.java:168) [MCXboxBroadcastStandalone.jar:?]
        at net.minecrell.terminalconsole.SimpleTerminalConsole.start(SimpleTerminalConsole.java:141) [MCXboxBroadcastStandalone.jar:?]
        at com.rtm516.mcxboxbroadcast.bootstrap.standalone.StandaloneMain.main(StandaloneMain.java:76) [MCXboxBroadcastStandalone.jar:?]
Caused by: java.lang.NumberFormatException: Expected an int but was 4294967284 at line 1 column 305 path $.availablePeopleSlots
        at com.google.gson.stream.JsonReader.nextInt(JsonReader.java:1264) ~[MCXboxBroadcastStandalone.jar:?]
        at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:275) ~[MCXboxBroadcastStandalone.jar:?]
        ... 16 more

Shows the friends amount like this 

[22:32:33 INFO]    Following: -1/1000

**Comment by rtm516** [comment]
So `4294967284` should be impossible as a number in that field, as it suggests you can have that many friends but the max xbox allows is 1000.
Can you restart the tool and check if it was just xbox doing strange things? If it keeps happening ill change the code to support this.

**Comment by mastachef** [comment]
Its not a one off issue, it continues to happen to all my accounts that have 1k friends (60+)

**Comment by Projecki** [comment]
I get the same error when using "accounts list" command

https://pastebin.com/nBRADUt3
