### ISSUE TITLE
Won't connect to world.

### ISSUE THREAD

**Issue by Log4Jake** [rtm516/MCXboxBroadcast#15]
I get this error when a player tries to connect. I am running spigot+geyser+floodgate
`[23:28:17] [Geyser Scheduled Thread-2-1/WARN]: [Geyser-Spigot] [MCXboxBroadcast] Failed to update session information!
com.rtm516.mcxboxbroadcast.core.exceptions.SessionUpdateException: Unable to update session information, got status 401 trying to update
        at com.rtm516.mcxboxbroadcast.core.SessionManager.updateSession(SessionManager.java:243) ~[?:?]
        at com.rtm516.mcxboxbroadcast.core.SessionManager.updateSession(SessionManager.java:210) ~[?:?]
        at com.rtm516.mcxboxbroadcast.bootstrap.geyser.MCXboxBroadcastExtension.tick(MCXboxBroadcastExtension.java:139) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.82.Final.jar:4.1.82.Final]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]`

**Comment by rtm516** [comment]
Please update to the latest version and enable debug logging to gather more information about this issue

**Comment by rtm516** [comment]
Closing due to no response by OP, please re-open if the error is still occurring
