### ISSUE TITLE
Failed to sync friends

### ISSUE THREAD

**Issue by yululiYT** [rtm516/MCXboxBroadcast#17]
Yesterday I suddenly started getting "Failed to sync friends" errors.
Is there any way to fix it?

**Comment by HeadHunterPvP** [comment]
I am having the same issue since yesterday. I read in issues #5 that they cleared the cache and it worked for them. However this is not working for me.

**Comment by yululiYT** [comment]
I have tried clearing the cache and re-logging in but to no avail....
But it worked with an account with no friends at all.

**Comment by yatooma25** [comment]
Same here, been getting this all day.

`2023-03-17 21:30:31.512 [ERROR] Failed to sync friends
com.rtm516.mcxboxbroadcast.core.exceptions.XboxFriendsException: chunked transfer encoding, state: READING_LENGTH
        at com.rtm516.mcxboxbroadcast.core.SessionManager.getXboxFriends(SessionManager.java:300)
        at com.rtm516.mcxboxbroadcast.bootstrap.standalone.StandaloneMain.lambda$main$1(StandaloneMain.java:104)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)`

**Comment by yululiYT** [comment]
Somehow it was cured. Perhaps it was an API failure or something... How about others?

**Comment by yatooma25** [comment]
> Somehow it was cured. Perhaps it was an API failure or something... How about others?

Likewise-- looks like mine is working! Must've been something on Microsoft's end.
