### ISSUE TITLE
download link is giving Origin is unreachable and the addon istelf is having websocket connection problems

### ISSUE THREAD

**Issue by apaddle** [rtm516/MCXboxBroadcast#26]
download link is broken and 

[MCXboxBroadcast] Connection to websocket lost, re-creating session...
[04:11:00 INFO] [geyser]: [MCXboxBroadcast] Re-connected!
[05:08:37 ERROR] [geyser]: [MCXboxBroadcast] Failed to update session information!
com.rtm516.mcxboxbroadcast.core.exceptions.SessionUpdateException: HTTP/1.1 header parser received no bytes
        at com.rtm516.mcxboxbroadcast.core.SessionManager.updateSession(SessionManager.java:238) ~[?:?]
        at com.rtm516.mcxboxbroadcast.core.SessionManager.updateSession(SessionManager.java:210) ~[?:?]
        at com.rtm516.mcxboxbroadcast.bootstrap.geyser.MCXboxBroadcastExtension.tick(MCXboxBroadcastExtension.java:139) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity.jar:3.2.0-SNAPSHOT (git-40b76c63-b256)]
        at java.lang.Thread.run(Thread.java:833) [?:?]
[06:04:36 INFO] [geyser]: [MCXboxBroadcast] Connection to websocket lost, re-creating session...
[06:04:37 INFO] [geyser]: [MCXboxBroadcast] Re-connected!
[06:20:47 ERROR] [geyser]: [MCXboxBroadcast] Failed to update session information!
com.rtm516.mcxboxbroadcast.core.exceptions.SessionUpdateException: HTTP/1.1 header parser received no bytes
        at com.rtm516.mcxboxbroadcast.core.SessionManager.updateSession(SessionManager.java:238) ~[?:?]
        at com.rtm516.mcxboxbroadcast.core.SessionManager.updateSession(SessionManager.java:210) ~[?:?]
        at com.rtm516.mcxboxbroadcast.bootstrap.geyser.MCXboxBroadcastExtension.tick(MCXboxBroadcastExtension.java:139) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity.jar:3.2.0-SNAPSHOT (git-40b76c63-b256)]
        at java.lang.Thread.run(Thread.java:833) [?:?]
[08:18:44 INFO] [geyser]: [MCXboxBroadcast] Connection to websocket lost, re-creating session...
[08:18:45 INFO] [geyser]: [MCXboxBroadcast] Re-connected!
[10:05:03 INFO] [geyser]: [MCXboxBroadcast] Connection to websocket lost, re-creating session...
[10:05:04 INFO] [geyser]: [MCXboxBroadcast] Re-connected!
[12:15:35 INFO] [geyser]: [MCXboxBroadcast] Connection to websocket lost, re-creating session...
[12:15:36 INFO] [geyser]: [MCXboxBroadcast] Re-connected!

**Comment by rtm516** [comment]
Origin is unreachable should be fixed
