### ISSUE TITLE
unable to work with paper mc server

### ISSUE THREAD

**Issue by UltraHispeed-Elite** [rtm516/MCXboxBroadcast#34]
this is the error message I get:

[20:14:48 ERROR]: An exception occurred while executing event GeyserPostInitializeEvent for subscriber org.geysermc.geyser.event.GeyserEventSubscriber
java.lang.NoSuchMethodError: 'void org.yaml.snakeyaml.parser.ParserImpl.<init>(org.yaml.snakeyaml.reader.StreamReader)'
	at com.fasterxml.jackson.dataformat.yaml.YAMLParser.<init>(YAMLParser.java:191) ~[?:?]
	at com.fasterxml.jackson.dataformat.yaml.YAMLFactory._createParser(YAMLFactory.java:504) ~[?:?]
	at com.fasterxml.jackson.dataformat.yaml.YAMLFactory.createParser(YAMLFactory.java:392) ~[?:?]
	at com.fasterxml.jackson.dataformat.yaml.YAMLFactory.createParser(YAMLFactory.java:15) ~[?:?]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3542) ~[?:?]
	at com.rtm516.mcxboxbroadcast.bootstrap.geyser.MCXboxBroadcastExtension.onPostInitialize(MCXboxBroadcastExtension.java:71) ~[?:?]
	at org.lanternpowered.lmbda.Lmbda$1.accept(Unknown Source) ~[Geyser-Spigot.jar:?]
	at org.geysermc.event.subscribe.impl.SubscriberImpl.lambda$new$0(SubscriberImpl.java:55) ~[Geyser-Spigot.jar:?]
	at org.geysermc.event.subscribe.impl.SubscriberImpl.invoke(SubscriberImpl.java:75) ~[Geyser-Spigot.jar:?]
	at org.geysermc.event.bus.impl.BaseBusImpl.fireSilently(BaseBusImpl.java:201) ~[Geyser-Spigot.jar:?]
	at org.geysermc.event.bus.impl.OwnedEventBusImpl.fireSilently(OwnedEventBusImpl.java:41) ~[Geyser-Spigot.jar:?]
	at org.geysermc.event.bus.impl.BaseBusImpl.fire(BaseBusImpl.java:180) ~[Geyser-Spigot.jar:?]
	at org.geysermc.event.bus.impl.OwnedEventBusImpl.fire(OwnedEventBusImpl.java:41) ~[Geyser-Spigot.jar:?]
	at org.geysermc.geyser.GeyserImpl.startInstance(GeyserImpl.java:524) ~[Geyser-Spigot.jar:?]
	at org.geysermc.geyser.GeyserImpl.initialize(GeyserImpl.java:217) ~[Geyser-Spigot.jar:?]
	at org.geysermc.geyser.GeyserImpl.start(GeyserImpl.java:713) ~[Geyser-Spigot.jar:?]
	at org.geysermc.geyser.platform.spigot.GeyserSpigotPlugin.postStartup(GeyserSpigotPlugin.java:216) ~[Geyser-Spigot.jar:?]
	at org.geysermc.geyser.platform.spigot.GeyserSpigotPlugin$1.onServerLoaded(GeyserSpigotPlugin.java:185) ~[Geyser-Spigot.jar:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:git-Paper-52]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.1.jar:git-Paper-52]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.1.jar:git-Paper-52]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:637) ~[paper-1.20.1.jar:git-Paper-52]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:435) ~[paper-1.20.1.jar:git-Paper-52]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.1.jar:git-Paper-52]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.20.1.jar:git-Paper-52]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-52]
	at java.lang.Thread.run(Thread.java:1623) ~[?:?]

**Comment by rtm516** [comment]
Fixed by https://github.com/rtm516/MCXboxBroadcast/commit/c7f5c087504af01b9fbb17996597c275ccd09a25
