### ISSUE TITLE
Disconnect issues

### ISSUE THREAD

**Issue by rtm516** [rtm516/MCXboxBroadcast#41]
I'm moving all the disconnect issues into this issue. Please follow the below if you wish to assist in getting to the bottom of this.
By disconnect issues I mean some people experience an issue where after some time the tool stops broadcasting on Xbox live without warning so stops appearing ingame, I've been unable to replicate this myself so if could follow the below it would likely help get the issue resolved faster.

1. Update to the latest build of MCXboxBroadcast
2. Enable debug logging
    * Extension: Set `debug-mode` to `true` in the Geyser config.yml
    * Standalone: Set `debug-log` to `true` in the config.yml
3. Wait for the disconnect issue to happen
4. Dump the current session information
    * Extension: `mcxboxbroadcast dumpsession` (in the server console)
    * Standalone: `dumpsession` (in the MCXboxBroadcast console)
3. Upload the logs along with the `lastSessionResponse.json` and `currentSessionResponse.json` files
    * Feel free to include any other information you feel is useful

**Comment by Agaloth** [comment]
I had this happening:
[22:32:45 WARN] [MCXboxBroadcast] Failed to add Joseachetto (2535425795164282) as a friend
[22:32:45 WARN] [MCXboxBroadcast] Failed to add Vertx sxv(1) (7039060735495561) as a friend
[22:33:06 WARN] [MCXboxBroadcast] Failed to add badrugbyboy27 (2535423032140551) as a friend
[22:33:06 WARN] [MCXboxBroadcast] Failed to add JackTacKenno (2535425135562570) as a friend
[22:33:06 WARN] [MCXboxBroadcast] Failed to add Atumalaca04629 (2535425469004006) as a friend
[22:33:06 WARN] [MCXboxBroadcast] Failed to add hairyhummus (2535448272166334) as a friend
[22:33:06 WARN] [MCXboxBroadcast] Failed to add King james5980 (2535409644444281) as a friend
[22:33:07 WARN] [MCXboxBroadcast] Failed to add rbknight12 (2535472951491061) as a friend
[22:33:07 WARN] [MCXboxBroadcast] Failed to add Azmodeux7490 (2535457435948057) as a friend
[22:33:07 WARN] [MCXboxBroadcast] Failed to add SWE Ellepelle (2535419152826625) as a friend
[22:33:07 WARN] [MCXboxBroadcast] Failed to add Gangluke8614 (2535444652931111) as a friend
[22:33:07 WARN] [MCXboxBroadcast] Failed to add Kat924676 (2535466864815122) as a friend
[22:33:07 WARN] [MCXboxBroadcast] Failed to add Wojciech2995 (2535439319059419) as a friend
[22:33:08 WARN] [MCXboxBroadcast] Failed to add XP E L S I R (2535473294663797) as a friend
[22:33:08 WARN] [MCXboxBroadcast] Failed to add Lufcjoe7 (2535442819958342) as a friend
[22:33:08 WARN] [MCXboxBroadcast] Failed to add PLIXY7062 (2535405670977169) as a friend


Here is the lastSessionResponse.json file: https://pastebin.com/qu31Tf81
and the currentSessionResponse.json file: https://pastebin.com/6RGuCgJx

**Comment by Agaloth** [comment]
ok i had the issue where mcxboxbroadcast wouldn't work again, but it doesn't let me run any commands so I can't even do ``mcxboxbroadcast dumpsession``

**Comment by rtm516** [comment]
> ok i had the issue where mcxboxbroadcast wouldn't work again, but it doesn't let me run any commands so I can't even do `mcxboxbroadcast dumpsession`

The fact the command isn't working suggests the tool has fully crashed which should be mentioned somewhere in the logs. Do you mind joining the discord to diagnose this more? If you could share debug logs for the tool that would be great.

**Comment by ofunny** [comment]
After my last report, I activated debug messages and restarted the standalone installation. Today, I checked the logs again and saw that after couple of hours of printing "Updated session!" each minute (my interval) it started to print 

`Connection to websocket lost, re-creating session...
Re-connected!`

every hour until I found it in that state and no other updates or anything in between, whereas it posted the update notification each minute before that started. Is this related to the current issue or another thing? Also a restart seems to fix it again.

**Comment by rtm516** [comment]
Interesting I wonder if the Auth tokens expired, can u share a zip of the cache files and logs privately via discord?
Wait until it next happens, stop the tool grab a zip of the files and send that over aswell as your local time and timezone and I should hopefully get to the bottom of it.

**Comment by PizzaThatCodes** [comment]
Was trying to help figure out the issue, after 2-3 hours (within those hours, not too sure exactly when due to not monitoring it) of the server running the disconnect happened. But too be fair at 2 hours in I noticed an notification from one of my bots that the internet went out so that was probably the cause of it all just stopping:

Server info:
Paper 1.20.1 latest version as of 2023-08-19 at roughly 11pm EST
Java 17.0.8 OpenJDK
Plugins:
  * GeyserMC
  * Floodgate
  * MCXboxBroadcast extension
  
When executing the `mcxboxbroadcast dumpsession` command, it said it generated the files but looking inside of `currentSessionResponse.json` it had nothing and for the `lastSessionResponse.json` it responded with:
`{"membersInfo":{"first":0,"next":1,"count":1,"accepted":1,"active":1},"constants":{"system":{"readyRemovalTimeout":240000,"reservedRemovalTimeout":240000,"sessionEmptyTimeout":0,"inactiveRemovalTimeout":300000,"version":1,"maxMembersCount":30,"visibility":"open","capabilities":{"connectivity":true,"connectionRequiredForActiveMembers":true,"gameplay":true,"crossPlay":true,"userAuthorizationStyle":true},"inviteProtocol":"game","memberInitialization":{"membersNeededToStart":1}},"custom":{}},"properties":{"system":{"joinRestriction":"followed","readRestriction":"followed","turn":[]},"custom":{"BroadcastSetting":3,"CrossPlayDisabled":false,"Joinability":"joinable_by_friends","LanGame":true,"MaxMemberCount":100,"MemberCount":0,"OnlineCrossPlatformGame":true,"SupportedConnections":[{"ConnectionType":6,"HostIpAddress":"MYSERVERIPADDRESS","HostPort":25566,"RakNetGUID":""}],"TitleId":0,"TransportLayer":0,"levelId":"level","hostName":"Geyser","ownerId":"2535456684763133","rakNetGUID":"83310600530722221009","worldName":"Another Geyser server.","worldType":"Survival","protocol":763,"version":"1.20"}},"servers":{},"members":{"0":{"next":1,"joinTime":"2023-08-19T03:04:15.6376459Z","constants":{"system":{"initialize":true,"xuid":"2535456684763133","index":0},"custom":{}},"properties":{"system":{"subscription":{"id":"845CC784-7348-4A27-BCDE-C083579DD113","changeTypes":["everything"]},"active":true,"connection":"e4c4af52-6564-460a-b178-9134c2fec810"},"custom":{}},"gamertag":"GoobConnect","activeTitleId":"1739947436"}},"correlationId":"cad31b83-edda-db8a-8c3a-046a81c26397","contractVersion":107,"branch":"b6cb9da6-fe85-4669-8581-dac2a6974e02","changeNumber":159,"startTime":"2023-08-19T03:04:15.6376459Z"}`
After the last websocket said anything, it then decided to stop working without saying anything, and I was just getting Geyser's Scoreboard updater.

Restarted the server and it had made it to `"changeNumber":1067` which is roughly 5-7 hours and it then happened again where there is the same issue but this time `com.rtm516.mcxboxbroadcast.core.exceptions.XboxFriendsException: null
        at com.rtm516.mcxboxbroadcast.core.SessionManager.getXboxFriends(SessionManager.java:312) ~[?:?]
        at com.rtm516.mcxboxbroadcast.core.FriendUtils.autoFriend(FriendUtils.java:15) ~[?:?]
        at com.rtm516.mcxboxbroadcast.bootstrap.geyser.MCXboxBroadcastExtension.lambda$createSession$3(MCXboxBroadcastExtension.java:189) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]`
		
At this point I think it happens when your internet goes out for 5 minutes or so which causes it to keep trying and then gives up or smth

If you need more info please let me know. If you want access to the server, it was running off of a panel I created and I can create you an user so you can view all files and mess around with it.

I will try this some more with a more stable internet connect though to see if it's more of just a network issue or not

**Comment by Pikachufan234** [comment]
Hello there. I have installed the extension to geyser and my friend, who plays on an xbox series s, sees the server in the friends section, as it should. However, he keeps on getting a message that says unable to connect to server. is there any way to fix this?

**Comment by rtm516** [comment]
> Hello there. I have installed the extension to geyser and my friend, who plays on an xbox series s, sees the server in the friends section, as it should. However, he keeps on getting a message that says unable to connect to server. is there any way to fix this?

This will be because the remote address needs setting in the config and not too with this issue. Please head over to discord if you get stuck

**Comment by JoshLoecker** [comment]
I'm also having these issues

Purpur server version 1.20.6
Geyser running in standalone mode, version 2.3.1
MCXboxBroadcast build 19 (released on Apr 21, 2024) in extension mode

lastSessionResponse.json: https://pastebin.com/F86WWj2d
currentSessionResponse.json was not created after running `mcxboxbroadcast dumpsession`
