### ISSUE TITLE
error sync

### ISSUE THREAD

**Issue by jefflima1** [rtm516/MCXboxBroadcast#45]
[15:30:23] [Geyser Scheduled Thread-2-1/WARN]: [Geyser-Spigot] [MCXboxBroadcast] Failed to sync friends
com.rtm516.mcxboxbroadcast.core.exceptions.XboxFriendsException: Illegal character ((CTRL-CHAR, code 31)): only regular white space (\r, \n, \t) is allowed between tokens
 at [Source: (String)"\u001F?\u0008\u0000\u0000\u0000\u0000\u0000\u0004\u0000?VJ?OIU?2402?QJI-N.?,(???S?RrK??IMQ(?W?L)J,IU??\u0003?"????T????b?Z\u0000?)?\u0019A\u0000\u0000\u0000"; line: 1, column: 2]
	at com.rtm516.mcxboxbroadcast.core.SessionManager.getXboxFriends(SessionManager.java:308) ~[?:?]
	at com.rtm516.mcxboxbroadcast.core.FriendUtils.autoFriend(FriendUtils.java:15) ~[?:?]
	at com.rtm516.mcxboxbroadcast.bootstrap.geyser.MCXboxBroadcastExtension.lambda$createSession$3(MCXboxBroadcastExtension.java:188) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[15:30:43] [Geyser Scheduled Thread-2-1/WARN]: [Geyser-Spigot] [MCXboxBroadcast] Failed to sync friends
com.rtm516.mcxboxbroadcast.core.exceptions.XboxFriendsException: Illegal character ((CTRL-CHAR, code 31)): only regular white space (\r, \n, \t) is allowed between tokens
 at [Source: (String)"\u001F?\u0008\u0000\u0000\u0000\u0000\u0000\u0004\u0000?VJ?OIU?2402?QJI-N.?,(???S?RrK??IMQ(?W?L)J,IU??\u0003?"????T????b?Z\u0000?)?\u0019A\u0000\u0000\u0000"; line: 1, column: 2]
	at com.rtm516.mcxboxbroadcast.core.SessionManager.getXboxFriends(SessionManager.java:308) ~[?:?]
	at com.rtm516.mcxboxbroadcast.core.FriendUtils.autoFriend(FriendUtils.java:15) ~[?:?]
	at com.rtm516.mcxboxbroadcast.bootstrap.geyser.MCXboxBroadcastExtension.lambda$createSession$3(MCXboxBroadcastExtension.java:188) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

I'm using the latest build version of mcxbox and geysermc, it was fine, but after restarting the error started to generate a lot of spam in the console

**Comment by rtm516** [comment]
Please enable debug in the geyser config file and then share the log, it should contain the response from xbox so I can debug the issue.
