### ISSUE TITLE
error upon login

### ISSUE THREAD

**Issue by hasankayra04** [rtm516/MCXboxBroadcast#46]
When i login using the code with a brand new acc, i get:
```
[06:14:50] [pool-18-thread-1/INFO] [Geyser-BungeeCord]: [MCXboxBroadcast] To sign in, use a web browser to open the page https://www.microsoft.com/link and enter the code *** to authenticate.
[06:16:58] [Thread-47/WARN] [Geyser-BungeeCord]: [MCXboxBroadcast] Failed to get SISU authentication token
com.rtm516.mcxboxbroadcast.shaded.com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
 at [Source: (String)""; line: 1, column: 0]
	at com.rtm516.mcxboxbroadcast.shaded.com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59) ~[?:?]
	at com.rtm516.mcxboxbroadcast.shaded.com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4821) ~[?:?]
	at com.rtm516.mcxboxbroadcast.shaded.com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4723) ~[?:?]
	at com.rtm516.mcxboxbroadcast.shaded.com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3677) ~[?:?]
	at com.rtm516.mcxboxbroadcast.shaded.com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3645) ~[?:?]
	at com.rtm516.mcxboxbroadcast.core.XboxTokenManager.getSISUToken(XboxTokenManager.java:267) ~[?:?]
	at com.rtm516.mcxboxbroadcast.core.SessionManager.getXboxToken(SessionManager.java:112) ~[?:?]
	at com.rtm516.mcxboxbroadcast.core.SessionManager.getXboxToken(SessionManager.java:116) ~[?:?]
	at com.rtm516.mcxboxbroadcast.core.SessionManager.createSession(SessionManager.java:149) ~[?:?]
	at com.rtm516.mcxboxbroadcast.core.SessionManager.createSession(SessionManager.java:138) ~[?:?]
	at com.rtm516.mcxboxbroadcast.bootstrap.geyser.MCXboxBroadcastExtension.createSession(MCXboxBroadcastExtension.java:176) ~[?:?]
	at com.rtm516.mcxboxbroadcast.bootstrap.geyser.MCXboxBroadcastExtension.lambda$onPostInitialize$2(MCXboxBroadcastExtension.java:168) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[06:16:58] [Thread-47/INFO] [Geyser-BungeeCord]: [MCXboxBroadcast] SISU authentication response is null, please login again
[06:16:58] [pool-19-thread-1/INFO] [Geyser-BungeeCord]: [MCXboxBroadcast] To sign in, use a web browser to open the page https://www.microsoft.com/link and enter the code ***L9E** to authenticate.

```

**Comment by rtm516** [comment]
Try clearing down your cache folder and the .json files within it.
Standalone `./cache/xxx.json`
Extension `./plugins/Geyser-xxx/extensions/MCXboxBroadcast/xxx.json`

**Comment by hasankayra04** [comment]
I switched over to standalone, and i am planing to keep use it as i like to have the extra motd thing when server is not reachable. Thanks anyway.

**Comment by hasankayra04** [comment]
Same thing is happening on standalone, tried removing cache folder.

**Comment by rtm516** [comment]
Did it work for a time or does it not work atall?

**Comment by hasankayra04** [comment]
When i complete the linking process it immediately spits out the same error. It was working fine 9 hour ago.

**Comment by rtm516** [comment]
Can you join the discord and drop me a DM so we can debug this live together?

**Comment by rtm516** [comment]
After chatting with @hasankayra04 this turned out to be caused by the system time not being accurate.

If you come across this error please check your servers clock is correct.
