### ISSUE TITLE
error

### ISSUE THREAD

**Issue by TypicalShavonne** [rtm516/MCXboxBroadcast#5]
2022-07-17 21:39:06.083 [ERROR] Failed to sync friends
com.rtm516.mcxboxbroadcast.core.exceptions.XboxFriendsException: No content to map due to end-of-input
 at [Source: (String)""; line: 1, column: 0]
        at com.rtm516.mcxboxbroadcast.core.SessionManager.getXboxFriends(SessionManager.java:300)
        at com.rtm516.mcxboxbroadcast.bootstrap.standalone.StandaloneMain.lambda$main$1(StandaloneMain.java:104)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by Creeperz653** [comment]
I cleared the cache and it fixed for me
