### ISSUE TITLE
Can both session accounts friend each other?

### ISSUE THREAD

**Issue by AxlRose-RX** [rtm516/MCXboxBroadcast#50]
I am getting:

[04:00:56] [Thread-7/INFO] [geyser]: [mcxboxbroadcast] [Primary Session] Starting SessionManager...
[04:00:56] [Thread-7/INFO] [geyser]: [mcxboxbroadcast] [Primary Session] Successfully authenticated as AxlRose6782 (2535456959930114)
[04:00:56] [Thread-7/INFO] [geyser]: [mcxboxbroadcast] [Primary Session] Creating Xbox LIVE session...
[04:00:57] [ForkJoinPool.commonPool-worker-1/INFO] [geyser]: Downloading Minecraft JAR to extract required files, please wait... (this may take some time depending on the speed of your internet connection)
[04:00:58] [Thread-7/INFO] [geyser]: [mcxboxbroadcast] [Primary Session] Creation of Xbox LIVE session was successful!
[04:00:58] [Thread-7/INFO] [geyser]: [mcxboxbroadcast] [Sub-Session CerealSeeker795] Starting SessionManager...
[04:00:58] [Thread-7/INFO] [geyser]: [mcxboxbroadcast] [Sub-Session CerealSeeker795] Successfully authenticated as CerealSeeker795 (2535405149804674)
[04:00:58] [MCXboxBroadcast Thread-1/WARN] [geyser]: [mcxboxbroadcast] [Sub-Session CerealSeeker795] Failed to add AxlRose6782 (2535456959930114) as a friend: (403) {"code":1000,"source":"PeopleFd","description":"Could not read XUID claim value","traceInformation":null}
[04:00:59] [Thread-7/INFO] [geyser]: [mcxboxbroadcast] [Sub-Session CerealSeeker795] Waiting for friendship to be processed...
[04:01:00] [Velocity Async Event Executor - #0/INFO] [com.velocitypowered.proxy.console.VelocityConsole]: Command is only for players.
[04:01:04] [Thread-7/INFO] [geyser]: [mcxboxbroadcast] [Sub-Session CerealSeeker795] Creating Xbox LIVE session...
[04:01:04] [Thread-7/ERROR] [geyser]: [mcxboxbroadcast] [Primary Session] Failed to create sub-session CerealSeeker795
com.rtm516.mcxboxbroadcast.core.exceptions.SessionUpdateException: Unable to update session information, got status 401 trying to update
	at com.rtm516.mcxboxbroadcast.core.SessionManagerCore.updateSessionInternal(SessionManagerCore.java:309) ~[?:?]
	at com.rtm516.mcxboxbroadcast.core.SubSessionManager.updateSession(SubSessionManager.java:52) ~[?:?]
	at com.rtm516.mcxboxbroadcast.core.SessionManagerCore.createSession(SessionManagerCore.java:223) ~[?:?]
	at com.rtm516.mcxboxbroadcast.core.SessionManagerCore.init(SessionManagerCore.java:174) ~[?:?]
	at com.rtm516.mcxboxbroadcast.core.SessionManager.init(SessionManager.java:98) ~[?:?]
	at com.rtm516.mcxboxbroadcast.bootstrap.geyser.MCXboxBroadcastExtension.createSession(MCXboxBroadcastExtension.java:164) ~[?:?]
	at com.rtm516.mcxboxbroadcast.bootstrap.geyser.MCXboxBroadcastExtension.lambda$onPostInitialize$3(MCXboxBroadcastExtension.java:156) ~[?:?]
	at java.lang.Thread.run(Thread.java:1623) [?:?]
[04:01:18] [Netty epoll Worker #1/INFO] [com.velocitypowered.proxy.connection.client.StatusSessionHandler]: [initial connection]

**Comment by rtm516** [comment]
The underlying error message is `Could not read XUID claim value` which I don't know what that means it's what Xbox is sending back.
Are both of your accounts fresh for this tool or nolonger used anywhere else?
Do they have any privacy settings that are not set to everyone/open?

**Comment by rtm516** [comment]
Confirmed fixed by user
