### ISSUE TITLE
Session information update failed.

### ISSUE THREAD

**Issue by Greenjp0025** [rtm516/MCXboxBroadcast#51]
[22:25:42 WARN]: [Geyser-Spigot] [mcxboxbroadcast] [Primary Session] Failed to update session information!
com.rtm516.mcxboxbroadcast.core.exceptions.SessionUpdateException: HTTP/1.1 header parser received no bytes                                                                                  
        at com.rtm516.mcxboxbroadcast.core.SessionManagerCore.updateSessionInternal(SessionManagerCore.java:304) ~[?:?]                                                                      
        at com.rtm516.mcxboxbroadcast.core.SessionManager.updateSession(SessionManager.java:130) ~[?:?]                                                                                      
        at com.rtm516.mcxboxbroadcast.core.SessionManager.updateSession(SessionManager.java:122) ~[?:?]                                                                                      
        at com.rtm516.mcxboxbroadcast.bootstrap.geyser.MCXboxBroadcastExtension.tick(MCXboxBroadcastExtension.java:181) ~[?:?]                                                               
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]                                                                                                    
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[?:?]                                                                                                           
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]                                                             
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]                                                                                            
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]                                                                                            
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by rtm516** [comment]
This seems to be something that happens I assume because of a rate limit in Xbox or something, unfortunately there isn't much I can do. It should sort its self out but may re-appear occationally.
