### ISSUE TITLE
Crash after signin

### ISSUE THREAD

**Issue by yuniruyuni** [rtm516/MCXboxBroadcast#67]
### what happen?
Using MCXboxBroadcast extension in Geyser-Spigot server, null pointer exception was happen after signin

```
[13:53:10 INFO]: [Geyser-Spigot] [mcxboxbroadcast] [Primary Session] To sign in, use a web browser to open the page https://www.microsoft.com/link and enter the code [-CODE-] to authenticate.

(I had logged in with above link, then...)

[13:54:40 WARN]: Exception in thread "Thread-38" java.lang.NullPointerException: Cannot read field "xui" because "tokenResponse.DisplayClaims" is null
[13:54:40 WARN]:        at com.rtm516.mcxboxbroadcast.core.XboxTokenManager.getXSTSToken(XboxTokenManager.java:179)
[13:54:40 WARN]:        at com.rtm516.mcxboxbroadcast.core.SessionManagerCore.getXboxToken(SessionManagerCore.java:139)
[13:54:40 WARN]:        at com.rtm516.mcxboxbroadcast.core.SessionManagerCore.init(SessionManagerCore.java:166)
[13:54:40 WARN]:        at com.rtm516.mcxboxbroadcast.core.SessionManager.init(SessionManager.java:82)
[13:54:40 WARN]:        at com.rtm516.mcxboxbroadcast.bootstrap.geyser.MCXboxBroadcastExtension.createSession(MCXboxBroadcastExtension.java:159)
[13:54:40 WARN]:        at com.rtm516.mcxboxbroadcast.bootstrap.geyser.MCXboxBroadcastExtension.lambda$onPostInitialize$3(MCXboxBroadcastExtension.java:151)
[13:54:40 WARN]:        at java.base/java.lang.Thread.run(Thread.java:840)
```

### used versions
- mcxboxbroadcast: Build 18 (master), `MCXboxBroadcastExtension.jar`
- Geyser-Spigot: Build #456 (2024/3/9)
- paper-mc: 1.20.4

**Comment by yuniruyuni** [comment]
ah... sorry this because I had not created Xbox gamer's tag.
