### ISSUE TITLE
Issue when connecting to microsoft account.

### ISSUE THREAD

**Issue by Isaac-Cooper** [rtm516/MCXboxBroadcast#68]
Hi, I have recently had this issue, it used to work fine before.

Error:
[18:33:55 ERROR] [Primary Session] Failed to get authentication token from device code
java.util.concurrent.ExecutionException: com.rtm516.mcxboxbroadcast.core.exceptions.LiveAuthenticationException: Failed to get authentication token while waiting for device: The user could not be authenticated or user interaction is required. The user must sign in again and if needed grant the client application access to the requested scope. (invalid_grant)
        at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
        at com.rtm516.mcxboxbroadcast.core.SessionManagerCore.getMsaToken(SessionManagerCore.java:115) [MCXboxBroadcastStandalone.jar:?]
        at com.rtm516.mcxboxbroadcast.core.SessionManagerCore.getXboxToken(SessionManagerCore.java:133) [MCXboxBroadcastStandalone.jar:?]
        at com.rtm516.mcxboxbroadcast.core.SessionManagerCore.init(SessionManagerCore.java:159) [MCXboxBroadcastStandalone.jar:?]
        at com.rtm516.mcxboxbroadcast.core.SessionManager.init(SessionManager.java:82) [MCXboxBroadcastStandalone.jar:?]
        at com.rtm516.mcxboxbroadcast.bootstrap.standalone.StandaloneMain.createSession(StandaloneMain.java:90) [MCXboxBroadcastStandalone.jar:?]
        at com.rtm516.mcxboxbroadcast.bootstrap.standalone.StandaloneMain.main(StandaloneMain.java:71) [MCXboxBroadcastStandalone.jar:?]
Caused by: com.rtm516.mcxboxbroadcast.core.exceptions.LiveAuthenticationException: Failed to get authentication token while waiting for device: The user could not be authenticated or user interaction is required. The user must sign in again and if needed grant the client application access to the requested scope. (invalid_grant)
        at com.rtm516.mcxboxbroadcast.core.LiveTokenManager.lambda$authDeviceCode$0(LiveTokenManager.java:172) ~[MCXboxBroadcastStandalone.jar:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
[18:33:56 ERROR] [Primary Session] Failed to get SISU authentication token
java.io.IOException: unexpected end of gzip stream
        at jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:586) ~[java.net.http:?]
        at jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:123) ~[java.net.http:?]
        at com.github.mizosoft.methanol.Methanol$InterceptorChain.forward(Methanol.java:828) ~[MCXboxBroadcastStandalone.jar:?]
        at com.github.mizosoft.methanol.Methanol$AutoDecompressingInterceptor.intercept(Methanol.java:937) ~[MCXboxBroadcastStandalone.jar:?]
        at com.github.mizosoft.methanol.Methanol$InterceptorChain.forward(Methanol.java:833) ~[MCXboxBroadcastStandalone.jar:?]
        at com.github.mizosoft.methanol.Methanol$RequestRewritingInterceptor.intercept(Methanol.java:881) ~[MCXboxBroadcastStandalone.jar:?]
        at com.github.mizosoft.methanol.Methanol$InterceptorChain.forward(Methanol.java:833) ~[MCXboxBroadcastStandalone.jar:?]
        at com.github.mizosoft.methanol.Methanol.send(Methanol.java:316) ~[MCXboxBroadcastStandalone.jar:?]
        at com.rtm516.mcxboxbroadcast.core.XboxTokenManager.getSISUToken(XboxTokenManager.java:229) [MCXboxBroadcastStandalone.jar:?]
        at com.rtm516.mcxboxbroadcast.core.SessionManagerCore.getXboxToken(SessionManagerCore.java:135) [MCXboxBroadcastStandalone.jar:?]
        at com.rtm516.mcxboxbroadcast.core.SessionManagerCore.init(SessionManagerCore.java:159) [MCXboxBroadcastStandalone.jar:?]
        at com.rtm516.mcxboxbroadcast.core.SessionManager.init(SessionManager.java:82) [MCXboxBroadcastStandalone.jar:?]
        at com.rtm516.mcxboxbroadcast.bootstrap.standalone.StandaloneMain.createSession(StandaloneMain.java:90) [MCXboxBroadcastStandalone.jar:?]
        at com.rtm516.mcxboxbroadcast.bootstrap.standalone.StandaloneMain.main(StandaloneMain.java:71) [MCXboxBroadcastStandalone.jar:?]
Caused by: java.io.EOFException: unexpected end of gzip stream
        at com.github.mizosoft.methanol.internal.decoder.GzipDecoder.decode(GzipDecoder.java:184) ~[MCXboxBroadcastStandalone.jar:?]
        at com.github.mizosoft.methanol.decoder.AsyncBodyDecoder.onComplete(AsyncBodyDecoder.java:196) ~[MCXboxBroadcastStandalone.jar:?]
        at jdk.internal.net.http.Http1Response$Http1BodySubscriber.complete(Http1Response.java:339) ~[java.net.http:?]
        at jdk.internal.net.http.Http1Response$Http1BodySubscriber.onComplete(Http1Response.java:390) ~[java.net.http:?]
        at jdk.internal.net.http.ResponseContent$ChunkedBodyParser.accept(ResponseContent.java:212) ~[java.net.http:?]
        at jdk.internal.net.http.ResponseContent$ChunkedBodyParser.accept(ResponseContent.java:129) ~[java.net.http:?]
        at jdk.internal.net.http.Http1Response$BodyReader.handle(Http1Response.java:790) ~[java.net.http:?]
        at jdk.internal.net.http.Http1Response$BodyReader.handle(Http1Response.java:720) ~[java.net.http:?]
        at jdk.internal.net.http.Http1Response$Receiver.accept(Http1Response.java:612) ~[java.net.http:?]
        at jdk.internal.net.http.Http1Response$BodyReader.tryAsyncReceive(Http1Response.java:750) ~[java.net.http:?]
        at jdk.internal.net.http.Http1AsyncReceiver.flush(Http1AsyncReceiver.java:233) ~[java.net.http:?]
        at jdk.internal.net.http.common.SequentialScheduler$LockingRestartableTask.run(SequentialScheduler.java:205) ~[java.net.http:?]
        at jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(SequentialScheduler.java:149) ~[java.net.http:?]
        at jdk.internal.net.http.common.SequentialScheduler$TryEndDeferredCompleter.complete(SequentialScheduler.java:347) ~[java.net.http:?]
        at jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(SequentialScheduler.java:151) ~[java.net.http:?]
        at jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:230) ~[java.net.http:?]
        at jdk.internal.net.http.HttpClientImpl$DelegatingExecutor.execute(HttpClientImpl.java:157) ~[java.net.http:?]
        at jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:305) ~[java.net.http:?]
        at jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:274) ~[java.net.http:?]
        at jdk.internal.net.http.Http1AsyncReceiver.asyncReceive(Http1AsyncReceiver.java:464) ~[java.net.http:?]
        at jdk.internal.net.http.Http1AsyncReceiver$Http1TubeSubscriber.onNext(Http1AsyncReceiver.java:584) ~[java.net.http:?]
        at jdk.internal.net.http.Http1AsyncReceiver$Http1TubeSubscriber.onNext(Http1AsyncReceiver.java:541) ~[java.net.http:?]
        at jdk.internal.net.http.common.SSLTube$DelegateWrapper.onNext(SSLTube.java:210) ~[java.net.http:?]
        at jdk.internal.net.http.common.SSLTube$SSLSubscriberWrapper.onNext(SSLTube.java:492) ~[java.net.http:?]
        at jdk.internal.net.http.common.SSLTube$SSLSubscriberWrapper.onNext(SSLTube.java:295) ~[java.net.http:?]
        at jdk.internal.net.http.common.SubscriberWrapper$DownstreamPusher.run1(SubscriberWrapper.java:316) ~[java.net.http:?]
        at jdk.internal.net.http.common.SubscriberWrapper$DownstreamPusher.run(SubscriberWrapper.java:259) ~[java.net.http:?]
        at jdk.internal.net.http.common.SequentialScheduler$LockingRestartableTask.run(SequentialScheduler.java:205) ~[java.net.http:?]
        at jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(SequentialScheduler.java:149) ~[java.net.http:?]
        at jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:230) ~[java.net.http:?]
        at jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:303) ~[java.net.http:?]
        at jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:256) ~[java.net.http:?]
        at jdk.internal.net.http.common.SubscriberWrapper.outgoing(SubscriberWrapper.java:232) ~[java.net.http:?]
        at jdk.internal.net.http.common.SubscriberWrapper.outgoing(SubscriberWrapper.java:198) ~[java.net.http:?]
        at jdk.internal.net.http.common.SSLFlowDelegate$Reader.processData(SSLFlowDelegate.java:444) ~[java.net.http:?]
        at jdk.internal.net.http.common.SSLFlowDelegate$Reader$ReaderDownstreamPusher.run(SSLFlowDelegate.java:268) ~[java.net.http:?]
        at jdk.internal.net.http.common.SequentialScheduler$LockingRestartableTask.run(SequentialScheduler.java:205) ~[java.net.http:?]
        at jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(SequentialScheduler.java:149) ~[java.net.http:?]
        at jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:230) ~[java.net.http:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
[18:33:56 INFO] [Primary Session] SISU authentication response is null, please login again

**Comment by rtm516** [comment]
Delete the auth token files and restart the tool to force reauthentication

**Comment by Isaac-Cooper** [comment]
I have already tried that,

**Comment by Isaac-Cooper** [comment]
I've tried like almost everything I could think of, I've ensured that the time is set right on the server and everything, I'm out of ideas.

**Comment by Isaac-Cooper** [comment]
[MCXboxBroadcastStandalone.jar:?]
Caused by: com.rtm516.mcxboxbroadcast.core.exceptions.LiveAuthenticationException: Failed to get authentication token while waiting for device: The user could not be authenticated or user interaction is required. The user must sign in again and if needed grant the client application access to the requested scope. (invalid_grant)
at com.rtm516.mcxboxbroadcast.core.LiveTokenManager.lambda$authDeviceCode$0(LiveTokenManager.java:172) ~[MCXboxBroadcastStandalone.jar:?]

**Comment by jstino** [comment]
Having the same issue, on a different computer it worked just fine, the next day it just doesn't anymore

**Comment by rtm516** [comment]
Still working fine for me, make sure you can login to https://account.xbox.com/en-gb/Profile?xr=mebarnav and make sure you don't get any warnings popping up

**Comment by rtm516** [comment]
I have added some more error code parsing to the tool can you update and confirm this is still an issue?

**Comment by Isaac-Cooper** [comment]
This is still an issue.

`
[22:47:01 WARN] Unknown channel option 'IP_DONTFRAG' for channel '[id: 0x02be378d]'
[22:47:01 INFO] [Primary Session] Starting SessionManager...
[22:47:02 INFO] [Primary Session] To sign in, use a web browser to open the page https://www.microsoft.com/link and enter the code 86K4QTWC to authenticate.
[22:47:49 ERROR] [Primary Session] Failed to get authentication token from device code: com.rtm516.mcxboxbroadcast.core.exceptions.LiveAuthenticationException: Failed to get authentication token while waiting for device: The user could not be authenticated or user interaction is required. The user must sign in again and if needed grant the client application access to the requested scope. (invalid_grant)
[22:47:49 INFO] [Primary Session] MSA authentication response is null, please login again
[22:47:49 INFO] [Primary Session] To sign in, use a web browser to open the page https://www.microsoft.com/link and enter the code W8D3CH36 to authenticate.
`

**Comment by rtm516** [comment]
Are you sure your connecting with a personal Microsoft account and not one bound to an organisation?
Did you also try the xbox.com link I sent to see if you can login there?
