### ISSUE TITLE
Session cannot be started.

### ISSUE THREAD

**Issue by RiverTeacher** [rtm516/MCXboxBroadcast#70]
The following error occurred and the system suddenly became unusable
```
[20:01:24 WARN]: [Geyser-Spigot] [mcxboxbroadcast] [Primary Session] Failed to get XSTS authentication token
java.net.http.HttpTimeoutException: request timed out
        at jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:571) ~[java.net.http:?]
        at jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:123) ~[java.net.http:?]
        at com.github.mizosoft.methanol.Methanol$InterceptorChain.forward(Methanol.java:828) ~[?:?]
        at com.github.mizosoft.methanol.Methanol$AutoDecompressingInterceptor.intercept(Methanol.java:937) ~[?:?]
        at com.github.mizosoft.methanol.Methanol$InterceptorChain.forward(Methanol.java:833) ~[?:?]
        at com.github.mizosoft.methanol.Methanol$RequestRewritingInterceptor.intercept(Methanol.java:881) ~[?:?]
        at com.github.mizosoft.methanol.Methanol$InterceptorChain.forward(Methanol.java:833) ~[?:?]
        at com.github.mizosoft.methanol.Methanol.send(Methanol.java:316) ~[?:?]
        at com.rtm516.mcxboxbroadcast.core.XboxTokenManager.getXSTSToken(XboxTokenManager.java:176) ~[?:?]
        at com.rtm516.mcxboxbroadcast.core.SessionManagerCore.getXboxToken(SessionManagerCore.java:139) ~[?:?]
        at com.rtm516.mcxboxbroadcast.core.SessionManagerCore.init(SessionManagerCore.java:166) ~[?:?]
        at com.rtm516.mcxboxbroadcast.core.SessionManager.init(SessionManager.java:82) ~[?:?]
        at com.rtm516.mcxboxbroadcast.bootstrap.geyser.MCXboxBroadcastExtension.createSession(MCXboxBroadcastExtension.java:159) ~[?:?]
        at com.rtm516.mcxboxbroadcast.bootstrap.geyser.MCXboxBroadcastExtension.lambda$onPostInitialize$3(MCXboxBroadcastExtension.java:151) ~[?:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
[20:01:24 WARN]: Exception in thread "Thread-18" java.lang.NullPointerException: Cannot invoke "com.rtm516.mcxboxbroadcast.core.models.auth.XboxTokenInfo.gamertag()" because "tokenInfo" is null
[20:01:24 WARN]:        at com.rtm516.mcxboxbroadcast.core.SessionManagerCore.init(SessionManagerCore.java:167)
[20:01:24 WARN]:        at com.rtm516.mcxboxbroadcast.core.SessionManager.init(SessionManager.java:82)
[20:01:24 WARN]:        at com.rtm516.mcxboxbroadcast.bootstrap.geyser.MCXboxBroadcastExtension.createSession(MCXboxBroadcastExtension.java:159)
[20:01:24 WARN]:        at com.rtm516.mcxboxbroadcast.bootstrap.geyser.MCXboxBroadcastExtension.lambda$onPostInitialize$3(MCXboxBroadcastExtension.java:151)
[20:01:24 WARN]:        at java.base/java.lang.Thread.run(Thread.java:840)
```

**Comment by rtm516** [comment]
The request to microsoft is timing out, either they are blocked by a firewall or have blocked/rate limited you. Nothing I can do about this.
