### ISSUE TITLE
java.lang.NullPointerException: Cannot read field "xui" because "tokenResponse.DisplayClaims" is null

### ISSUE THREAD

**Issue by alfonsojon** [rtm516/MCXboxBroadcast#71]
I'm getting the following error after getting a token - hoping to find out if others are having this issue or if there is a fix.

`[22:00:56 WARN]: Exception in thread "Thread-51" java.lang.NullPointerException: Cannot read field "xui" because "tokenResponse.DisplayClaims" is null
[22:00:56 WARN]:        at com.rtm516.mcxboxbroadcast.core.XboxTokenManager.getXSTSToken(XboxTokenManager.java:179)
[22:00:56 WARN]:        at com.rtm516.mcxboxbroadcast.core.SessionManagerCore.getXboxToken(SessionManagerCore.java:139)
[22:00:56 WARN]:        at com.rtm516.mcxboxbroadcast.core.SessionManagerCore.init(SessionManagerCore.java:166)
[22:00:56 WARN]:        at com.rtm516.mcxboxbroadcast.core.SessionManager.init(SessionManager.java:82)
[22:00:56 WARN]:        at com.rtm516.mcxboxbroadcast.bootstrap.geyser.MCXboxBroadcastExtension.createSession(MCXboxBroadcastExtension.java:159)
[22:00:56 WARN]:        at com.rtm516.mcxboxbroadcast.bootstrap.geyser.MCXboxBroadcastExtension.lambda$onPostInitialize$3(MCXboxBroadcastExtension.java:151)
[22:00:56 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)`

**Comment by rtm516** [comment]
Have you used the tool before? If not are you sure you setup xbox on the Microsoft account your using?

**Comment by alfonsojon** [comment]
I have not. What setup with Xbox is required?

**Comment by rtm516** [comment]
Login to https://www.xbox.com/ sign in to your Microsoft account and create an xbox profile
