### ISSUE TITLE
Error in console: Failed to refresh Live token

### ISSUE THREAD

**Issue by tumblinpanda** [rtm516/MCXboxBroadcast#73]
[19:38:58 WARN]: [Geyser-Spigot] [mcxboxbroadcast] [Primary Session] Failed to refresh Live token
java.net.http.HttpConnectTimeoutException: HTTP connect timed out
        at jdk.internal.net.http.HttpClientImpl.send(Unknown Source) ~[java.net.http:?]
        at jdk.internal.net.http.HttpClientFacade.send(Unknown Source) ~[java.net.http:?]
        at com.github.mizosoft.methanol.Methanol$InterceptorChain.forward(Methanol.java:828) ~[?:?]
        at com.github.mizosoft.methanol.Methanol$AutoDecompressingInterceptor.intercept(Methanol.java:937) ~[?:?]
        at com.github.mizosoft.methanol.Methanol$InterceptorChain.forward(Methanol.java:833) ~[?:?]
        at com.github.mizosoft.methanol.Methanol$RequestRewritingInterceptor.intercept(Methanol.java:881) ~[?:?]
        at com.github.mizosoft.methanol.Methanol$InterceptorChain.forward(Methanol.java:833) ~[?:?]
        at com.github.mizosoft.methanol.Methanol.send(Methanol.java:316) ~[?:?]
        at com.rtm516.mcxboxbroadcast.core.LiveTokenManager.refreshToken(LiveTokenManager.java:99) ~[?:?]
        at com.rtm516.mcxboxbroadcast.core.LiveTokenManager.verifyTokens(LiveTokenManager.java:60) ~[?:?]
        at com.rtm516.mcxboxbroadcast.core.SessionManagerCore.getMsaToken(SessionManagerCore.java:111) ~[?:?]
        at com.rtm516.mcxboxbroadcast.core.SessionManagerCore.getXboxToken(SessionManagerCore.java:134) ~[?:?]
        at com.rtm516.mcxboxbroadcast.core.SessionManagerCore.init(SessionManagerCore.java:166) ~[?:?]
        at com.rtm516.mcxboxbroadcast.core.SessionManager.init(SessionManager.java:82) ~[?:?]
        at com.rtm516.mcxboxbroadcast.bootstrap.geyser.MCXboxBroadcastExtension.createSession(MCXboxBroadcastExtension.java:159) ~[?:?]
        at com.rtm516.mcxboxbroadcast.bootstrap.geyser.MCXboxBroadcastExtension.lambda$onPostInitialize$3(MCXboxBroadcastExtension.java:151) ~[?:?]
        at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.net.http.HttpConnectTimeoutException: HTTP connect timed out
        at jdk.internal.net.http.ResponseTimerEvent.handle(Unknown Source) ~[java.net.http:?]
        at jdk.internal.net.http.HttpClientImpl.purgeTimeoutsAndReturnNextDeadline(Unknown Source) ~[java.net.http:?]
        at jdk.internal.net.http.HttpClientImpl$SelectorManager.run(Unknown Source) ~[java.net.http:?]
Caused by: java.net.ConnectException: HTTP connect timed out
        at jdk.internal.net.http.ResponseTimerEvent.handle(Unknown Source) ~[java.net.http:?]
        at jdk.internal.net.http.HttpClientImpl.purgeTimeoutsAndReturnNextDeadline(Unknown Source) ~[java.net.http:?]
        at jdk.internal.net.http.HttpClientImpl$SelectorManager.run(Unknown Source) ~[java.net.http:?]

**Comment by rtm516** [comment]
Changed over the authentication library in 22af2a3 please update and retry
