### ISSUE TITLE
Console error on standalone : Failed to ping server

### ISSUE THREAD

**Issue by EtoyJan** [rtm516/MCXboxBroadcast#75]
Hello. I'm using MCXboxBroadcast's Build 19. However, when I start it up and update the session, I get the error Failed to ping server. This is the error that appears in the console.

[ERROR] [Primary Session] Failed to ping server
java.util.concurrent.ExecutionException: java.util.concurrent.TimeoutException
        at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
        at com.rtm516.mcxboxbroadcast.bootstrap.standalone.StandaloneMain.updateSessionInfo(StandaloneMain.java:115) ~[MCXboxBroadcastStandalone.jar:?]
        at com.rtm516.mcxboxbroadcast.bootstrap.standalone.StandaloneMain.lambda$createSession$0(StandaloneMain.java:93) ~[MCXboxBroadcastStandalone.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.util.concurrent.TimeoutException
        at com.nukkitx.network.raknet.RakNetClient.onTick(RakNetClient.java:121) ~[MCXboxBroadcastStandalone.jar:?]
        at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) ~[MCXboxBroadcastStandalone.jar:?]
        at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:159) ~[MCXboxBroadcastStandalone.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[MCXboxBroadcastStandalone.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[MCXboxBroadcastStandalone.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[MCXboxBroadcastStandalone.jar:?]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[MCXboxBroadcastStandalone.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[MCXboxBroadcastStandalone.jar:?]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[MCXboxBroadcastStandalone.jar:?]
        ... 1 more

**Comment by rtm516** [comment]
Are you sure you have the correct IP and port forwarding the bedrock/geyser server in the config?

**Comment by EtoyJan** [comment]
yes. The config is set correctly.

**Comment by rtm516** [comment]
Then either the server isn't running or the tool can't reach it. Please use https://mcsrvstat.us/ with the bedrock server box checked to confirm if the server is pingable for bedrock players.

**Comment by EtoyJan** [comment]
The error persists even after starting the server.
When I accessed my server at https://mcsrvstat.us it displayed correctly.

**Comment by rtm516** [comment]
Can you provide a screenshot of that page and a copy of the config?

**Comment by EtoyJan** [comment]
![Minecraft Server Status](https://github.com/rtm516/MCXboxBroadcast/assets/168520943/a5fa226b-cab2-4f68-9b4d-c5b5a6662df9)
![config yml](https://github.com/rtm516/MCXboxBroadcast/assets/168520943/a36f5578-60f7-43a6-96d9-45b1bf088784)

**Comment by SonnenPingu** [comment]
I've had that before. 

In the end, it was because of where I had installed mcxboxbroadcast standalone. 
Authentication with ms worked but the ping to the server did not work.
Then I just unlocked the port in the firewall and then it worked. 

Feel free to test if you can find the following server:
176.57.160.50 Port 32466 
(It's a public ip anyway and I'll deactivate the service behind it as soon as I get feedback that works or doesn't work) 

If this is also not pingable for you, then there is an error somewhere with you where mcxboxbroadcast is installed.

Sometimes the firewall where the mc server is located can also prevent the query query from working but mcxboxbroadcast cannot ping

Greetings

**Comment by EtoyJan** [comment]
It was successful without any errors. I'm really thankful to you.

**Comment by SonnenPingu** [comment]
Note that the server is no longer active. The ip was meant for you as a test.

**Comment by SonnenPingu** [comment]
Note that the server is no longer active. The ip was meant for you as a test.
