### ISSUE TITLE
Stuck on connecting to multiplayer game [Standalone]

### ISSUE THREAD

**Issue by Ryuo1** [rtm516/MCXboxBroadcast#77]
I can connect to other server IP's correctly, but not mine. My server is running behind IPv6 with the java flag `-Djava.net.preferIPv6Addresses=true`, but I don't know it that is the cause of the issue.

```
> dumpsession
[20:58:11 INFO] [Primary Session] Dumping current and last session responses
[20:58:11 ERROR] Failed to execute command
java.lang.IllegalArgumentException: Malformed escape pair at index 131: https://sessiondirectory.xboxlive.com/serviceconfigs/4fc10100-5f7a-4470-899b-280835760c07/sessionTemplates/MinecraftLobby/sessions/%s95460c61-899d-4d11-8c0c-67d6071fc7b3
        at java.net.URI.create(URI.java:932) ~[?:?]
        at com.rtm516.mcxboxbroadcast.core.SessionManager.dumpSession(SessionManager.java:177) ~[MCXboxBroadcastStandalone.jar:?]
        at com.rtm516.mcxboxbroadcast.bootstrap.standalone.StandaloneLoggerImpl.runCommand(StandaloneLoggerImpl.java:75) [MCXboxBroadcastStandalone.jar:?]
        at net.minecrell.terminalconsole.SimpleTerminalConsole.processInput(SimpleTerminalConsole.java:87) [MCXboxBroadcastStandalone.jar:?]
        at net.minecrell.terminalconsole.SimpleTerminalConsole.readCommands(SimpleTerminalConsole.java:168) [MCXboxBroadcastStandalone.jar:?]
        at net.minecrell.terminalconsole.SimpleTerminalConsole.start(SimpleTerminalConsole.java:141) [MCXboxBroadcastStandalone.jar:?]
        at com.rtm516.mcxboxbroadcast.bootstrap.standalone.StandaloneMain.main(StandaloneMain.java:73) [MCXboxBroadcastStandalone.jar:?]
Caused by: java.net.URISyntaxException: Malformed escape pair at index 131: https://sessiondirectory.xboxlive.com/serviceconfigs/4fc10100-5f7a-4470-899b-280835760c07/sessionTemplates/MinecraftLobby/sessions/%s95460c61-899d-4d11-8c0c-67d6071fc7b3
        at java.net.URI$Parser.fail(URI.java:2995) ~[?:?]
        at java.net.URI$Parser.scanEscape(URI.java:3123) ~[?:?]
        at java.net.URI$Parser.scan(URI.java:3146) ~[?:?]
        at java.net.URI$Parser.checkChars(URI.java:3164) ~[?:?]
        at java.net.URI$Parser.parseHierarchical(URI.java:3248) ~[?:?]
        at java.net.URI$Parser.parse(URI.java:3196) ~[?:?]
        at java.net.URI.<init>(URI.java:645) ~[?:?]
        at java.net.URI.create(URI.java:930) ~[?:?]
        ... 6 more
```

The server is joinable from the server menu of the game.

**Comment by Ryuo1** [comment]
After enclosing the server ip in the config in quotes, i get the following errors in console:
```
[22:12:44 ERROR] [Primary Session] Failed to ping server
java.util.concurrent.ExecutionException: java.util.concurrent.TimeoutException
        at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
        at com.rtm516.mcxboxbroadcast.bootstrap.standalone.StandaloneMain.updateSessionInfo(StandaloneMain.java:115) ~[MCXboxBroadcastStandalone.jar:?]
        at com.rtm516.mcxboxbroadcast.bootstrap.standalone.StandaloneMain.lambda$createSession$0(StandaloneMain.java:93) ~[MCXboxBroadcastStandalone.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1575) [?:?]
Caused by: java.util.concurrent.TimeoutException
        at com.nukkitx.network.raknet.RakNetClient.onTick(RakNetClient.java:121) ~[MCXboxBroadcastStandalone.jar:?]
        at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) ~[MCXboxBroadcastStandalone.jar:?]
        at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:159) ~[MCXboxBroadcastStandalone.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[MCXboxBroadcastStandalone.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[MCXboxBroadcastStandalone.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[MCXboxBroadcastStandalone.jar:?]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:406) ~[MCXboxBroadcastStandalone.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[MCXboxBroadcastStandalone.jar:?]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[MCXboxBroadcastStandalone.jar:?]
        ... 1 more
```

**Comment by Ryuo1** [comment]
Further diagnosis reveals that it may be an issue with IPv6.

**Comment by SonnenPingu** [comment]
As far as I know, bedrock can't do an ivp6 

Therefore, mcxboxbroadcast will not be able to do ivp6 either.

**Comment by Ryuo1** [comment]
I can join my ipv6 server from the servers tab though

**Comment by rtm516** [comment]
Please update, confirm the issue still happens and then provide a session dump

**Comment by Ryuo1** [comment]
i dont want to worry about this again.
mental health hitting hard 😁
