### ISSUE TITLE
NullPointerException - Just Linked to Microsoft Acc

### ISSUE THREAD

**Issue by Goblom** [rtm516/MCXboxBroadcast#80]
Just linked to Microsoft Account. 

```
[22:52:55] [Thread-18/WARN]: Exception in thread "Thread-18" java.lang.NullPointerException: Cannot read field "xui" because "tokenResponse.DisplayClaims" is null

[22:52:55] [Thread-18/WARN]: 	at com.rtm516.mcxboxbroadcast.core.XboxTokenManager.getXSTSToken(XboxTokenManager.java:179)
[22:52:55] [Thread-18/WARN]: 	at com.rtm516.mcxboxbroadcast.core.SessionManagerCore.getXboxToken(SessionManagerCore.java:139)
[22:52:55] [Thread-18/WARN]: 	at com.rtm516.mcxboxbroadcast.core.SessionManagerCore.init(SessionManagerCore.java:166)
[22:52:55] [Thread-18/WARN]: 	at com.rtm516.mcxboxbroadcast.core.SessionManager.init(SessionManager.java:82)
[22:52:55] [Thread-18/WARN]: 	at com.rtm516.mcxboxbroadcast.bootstrap.geyser.MCXboxBroadcastExtension.createSession(MCXboxBroadcastExtension.java:159)
[22:52:55] [Thread-18/WARN]: 	at com.rtm516.mcxboxbroadcast.bootstrap.geyser.MCXboxBroadcastExtension.lambda$onPostInitialize$3(MCXboxBroadcastExtension.java:151)
[22:52:55] [Thread-18/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1570)```

**Comment by SonnenPingu** [comment]
Standalone or extension

Have you ever tried a restart after left? Does the same thing appear then?

**Comment by Goblom** [comment]
Extension.

I tried restarting and reloading server as well as the restart command.

I also don't have bungeecord. Just a spigot server.

**Comment by rtm516** [comment]
This sort of error normally appears if the account has not had an Xbox live profile setup. I suggest logging into the account on xbox.com and making sure it's setup an Xbox profile for you.

**Comment by Goblom** [comment]
You would be correct. I do not have Xbox live on the account I'm trying to use. I'll have to see about justifying the cost.

Thankyou!

**Comment by sennby** [comment]
I couldnt get extension to work whatsoever.
Use standalone and itll work.

**Comment by rtm516** [comment]
> You would be correct. I do not have Xbox live on the account I'm trying to use. I'll have to see about justifying the cost.
> 
> Thankyou!

Setting up xbox live profile is free you don't need a membership or anything
https://account.xbox.com/en-gb/Profile?xr=mebarnav
