### ISSUE TITLE
Unable to connect to world

### ISSUE THREAD

**Issue by sennby** [rtm516/MCXboxBroadcast#82]
I use standalone and i changed my ip and port to a few things and cant connect. The geyser server has multiple people connected just fine right now and so does java. Add friend works for people but then they get Unable to connect to world.

Any ideas what im doing wrong or what to try

**Comment by sennby** [comment]
dumpsession
[00:06:35 INFO] [Primary Session] Dumping current and last session responses
[00:06:35 ERROR] Failed to execute command
java.lang.IllegalArgumentException: Malformed escape pair at index 131: https://sessiondirectory.xboxlive.com/serviceconfigs/4fc10100-5f7a-4470-899b-280835760c07/sessionTemplates/MinecraftLobby/sessions/%s85bac5b1-f567-413e-99ed-71c3ee18973a
        at java.net.URI.create(URI.java:932) ~[?:?]
        at com.rtm516.mcxboxbroadcast.core.SessionManager.dumpSession(SessionManager.java:177) ~[MCXboxBroadcastStandalone.jar:?]
        at com.rtm516.mcxboxbroadcast.bootstrap.standalone.StandaloneLoggerImpl.runCommand(StandaloneLoggerImpl.java:75) [MCXboxBroadcastStandalone.jar:?]
        at net.minecrell.terminalconsole.SimpleTerminalConsole.processInput(SimpleTerminalConsole.java:87) [MCXboxBroadcastStandalone.jar:?]
        at net.minecrell.terminalconsole.SimpleTerminalConsole.readCommands(SimpleTerminalConsole.java:181) [MCXboxBroadcastStandalone.jar:?]
        at net.minecrell.terminalconsole.SimpleTerminalConsole.start(SimpleTerminalConsole.java:143) [MCXboxBroadcastStandalone.jar:?]
        at com.rtm516.mcxboxbroadcast.bootstrap.standalone.StandaloneMain.main(StandaloneMain.java:73) [MCXboxBroadcastStandalone.jar:?]
Caused by: java.net.URISyntaxException: Malformed escape pair at index 131: https://sessiondirectory.xboxlive.com/serviceconfigs/4fc10100-5f7a-4470-899b-280835760c07/sessionTemplates/MinecraftLobby/sessions/%s85bac5b1-f567-413e-99ed-71c3ee18973a
        at java.net.URI$Parser.fail(URI.java:2995) ~[?:?]
        at java.net.URI$Parser.scanEscape(URI.java:3123) ~[?:?]
        at java.net.URI$Parser.scan(URI.java:3146) ~[?:?]
        at java.net.URI$Parser.checkChars(URI.java:3164) ~[?:?]
        at java.net.URI$Parser.parseHierarchical(URI.java:3248) ~[?:?]
        at java.net.URI$Parser.parse(URI.java:3196) ~[?:?]
        at java.net.URI.<init>(URI.java:645) ~[?:?]
        at java.net.URI.create(URI.java:930) ~[?:?]
        ... 6 more

**Comment by sennby** [comment]
I deleted all. relinked. same issues. still cant dumpsession.

**Comment by sennby** [comment]
With the new build i can now dumpsession:
[currentSessionResponse.json](https://github.com/user-attachments/files/15744227/curren
[lastSessionResponse.json](https://github.com/user-attachments/files/15744228/lastSessionResponse.json)
tSessionResponse.json)

**Comment by rtm516** [comment]
Adding your bot and joining through it is working fine for me

**Comment by sennby** [comment]
> Adding your bot and joining through it is working fine for me

dumpsession fix resolved the issue then it seems.
