### ISSUE TITLE
Can't be loaded by the server

### ISSUE THREAD

**Issue by Xirano56** [rtm516/MCXboxBroadcast#90]
While trying to open the server it gaves the error that it can't load MCXboxBroadcast, I seted up the account and java-server adresses', but it can't load:
Dump:
[19:38:56] [main/ERROR]: Couldn't load MCXboxBroadcastStandalone.jar in folder /home/container/./config/Geyser-Fabric/extensions/MCXboxBroadcastStandalone.jar:
org.geysermc.geyser.api.extension.exception.InvalidDescriptionException: Failed to load extension description for ./config/Geyser-Fabric/extensions/MCXboxBroadcastStandalone.jar
        at org.geysermc.geyser.extension.GeyserExtensionLoader.extensionDescription(GeyserExtensionLoader.java:118) ~[Geyser-Fabric.jar:?]
        at org.geysermc.geyser.extension.GeyserExtensionLoader.lambda$loadAllExtensions$0(GeyserExtensionLoader.java:170) ~[Geyser-Fabric.jar:?]
        at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
        at org.geysermc.geyser.extension.GeyserExtensionLoader.loadAllExtensions(GeyserExtensionLoader.java:158) ~[Geyser-Fabric.jar:?]
        at org.geysermc.geyser.api.extension.ExtensionManager.loadAllExtensions(ExtensionManager.java:88) ~[Geyser-Fabric.jar:?]
        at org.geysermc.geyser.extension.GeyserExtensionManager.init(GeyserExtensionManager.java:48) ~[Geyser-Fabric.jar:?]
        at org.geysermc.geyser.GeyserImpl.<init>(GeyserImpl.java:197) ~[Geyser-Fabric.jar:?]
        at org.geysermc.geyser.GeyserImpl.load(GeyserImpl.java:779) ~[Geyser-Fabric.jar:?]
        at org.geysermc.geyser.platform.mod.GeyserModBootstrap.onGeyserInitialize(GeyserModBootstrap.java:96) ~[Geyser-Fabric.jar:?]
        at org.geysermc.geyser.platform.fabric.GeyserFabricBootstrap.onInitialize(GeyserFabricBootstrap.java:72) ~[Geyser-Fabric.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) [fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) [fabric-loader-0.15.11.jar:?]
        at net.minecraft.server.Main.main(Main.java:111) [server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) [fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.15.11.jar:?]
Caused by: java.nio.file.NoSuchFileException: /extension.yml
        at jdk.zipfs@21.0.3/jdk.nio.zipfs.ZipFileSystem.newInputStream(ZipFileSystem.java:861) ~[jdk.zipfs:?]
        at jdk.zipfs@21.0.3/jdk.nio.zipfs.ZipPath.newInputStream(ZipPath.java:751) ~[jdk.zipfs:?]
        at jdk.zipfs@21.0.3/jdk.nio.zipfs.ZipFileSystemProvider.newInputStream(ZipFileSystemProvider.java:270) ~[jdk.zipfs:?]
        at java.base/java.nio.file.Files.newInputStream(Files.java:159) ~[?:?]
        at java.base/java.nio.file.Files.newBufferedReader(Files.java:2897) ~[?:?]
        at java.base/java.nio.file.Files.newBufferedReader(Files.java:2930) ~[?:?]
        at org.geysermc.geyser.extension.GeyserExtensionLoader.extensionDescription(GeyserExtensionLoader.java:114) ~[Geyser-Fabric.jar:?]
        ... 16 more

**Comment by rtm516** [comment]
Your trying to load the standalone version as an extension, please download the `MCXboxBroadcastExtension.jar` instead

**Comment by Xirano56** [comment]
thanks, I am dumb
