### ISSUE TITLE
"Outdated Client" when joining via MCXboxBroadcast - MC v1.21.0

### ISSUE THREAD

**Issue by TDGalea** [rtm516/MCXboxBroadcast#91]
At least I _think_ this is the case. I've worked it down to seemingly just MCXboxBroadcast being the weak link now.

Paper has finally released some early 1.21 builds. They work on Java.
BungeeCord (I know... I wanna migrate some time) is working.
Geyser itself as well as Floodgate are working - Bedrock can join if the server is added manually.

But, joining via MCXboxBroadcast has it say "Outdated client".

Downloaded the build released an hour ago as of writing. Still the same.
My apologies if this is just a case of the plugin needing to be updated to support 1.21, but I've not had this plugin do this before so just wanted to raise awareness.

**Comment by rtm516** [comment]
This was an issue when 1.21 came out but should have been fixed in build 21 and https://github.com/rtm516/MCXboxBroadcast/commit/d00bd20b28f2c5080e608ddbd47511d72687769b

Are you sure you are downloading the latest? (27 or 28)

**Comment by rtm516** [comment]
Can you provide a sesssion dump?
`mcxboxbroadcast dumpsession`

**Comment by TDGalea** [comment]
Well...

```
>mcxboxbroadcast dumpsession
09:26:04 [INFO] [Geyser-BungeeCord] [mcxboxbroadcast] [Primary Session] Dumping current and last session responses
09:26:04 [INFO] An internal error occurred whilst executing this command, please check the console log for details.
09:26:04 [WARNING] Error in dispatching command
java.lang.IllegalArgumentException: Malformed escape pair at index 131: https://sessiondirectory.xboxlive.com/serviceconfigs/4fc10100-5f7a-4470-899b-280835760c07/sessionTemplates/MinecraftLobby/sessions/%sbb75f897-2390-49ea-9c96-bbdee08d8239
    at java.base/java.net.URI.create(URI.java:932)
    at com.rtm516.mcxboxbroadcast.core.SessionManager.dumpSession(SessionManager.java:173)
    at com.rtm516.mcxboxbroadcast.bootstrap.geyser.MCXboxBroadcastExtension.lambda$onCommandDefine$1(MCXboxBroadcastExtension.java:56)
    at org.geysermc.geyser.command.GeyserCommandManager$CommandBuilder$1.execute(GeyserCommandManager.java:294)
    at org.geysermc.geyser.platform.bungeecord.command.GeyserBungeeCommandExecutor.execute(GeyserBungeeCommandExecutor.java:71)
    at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:208)
    at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:158)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:74)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
Caused by: java.net.URISyntaxException: Malformed escape pair at index 131: https://sessiondirectory.xboxlive.com/serviceconfigs/4fc10100-5f7a-4470-899b-280835760c07/sessionTemplates/MinecraftLobby/sessions/%sbb75f897-2390-49ea-9c96-bbdee08d8239
    at java.base/java.net.URI$Parser.fail(URI.java:2995)
    at java.base/java.net.URI$Parser.scanEscape(URI.java:3123)
    at java.base/java.net.URI$Parser.scan(URI.java:3146)
    at java.base/java.net.URI$Parser.checkChars(URI.java:3164)
    at java.base/java.net.URI$Parser.parseHierarchical(URI.java:3248)
    at java.base/java.net.URI$Parser.parse(URI.java:3196)
    at java.base/java.net.URI.<init>(URI.java:645)
    at java.base/java.net.URI.create(URI.java:930)
    ... 8 more
>
```

**Comment by TDGalea** [comment]
Right, well I went and did the biz again. This time, instead of claiming I'm on an outdated client, it just fails to connect to world.

Yet again this is exclusive to joining via the Xbox account. If I join by adding as a server, it works fine.

**Comment by rtm516** [comment]
Can you provide a session dump now?

**Comment by TDGalea** [comment]
Two successful dumps this time.

[currentSessionResponse.json](https://github.com/user-attachments/files/15912944/currentSessionResponse.json)
[lastSessionResponse.json](https://github.com/user-attachments/files/15912945/lastSessionResponse.json)

**Comment by rtm516** [comment]
The connection issue you are getting is due to the server broadcasting `192.168.1.251` as the IP, you need to alter the extension config `remote-address` to the IP that users connect to

**Comment by rtm516** [comment]
The `auto` setting hasnt changed in 2 years. It will default to the geyser listen address and then try and find out what interface leads out onto the internet. Its something I should likely change to use `https://ipv4.icanhazip.com/` instead

**Comment by TDGalea** [comment]
You are the one and only other person I've seen use icanhazip. +1.

I find it odd that auto's suddenly not working though without you changing anything. Perhaps Geyser themselves have broken something ¯⁠\⁠_⁠(⁠ツ⁠)⁠_⁠/⁠¯

**Comment by TDGalea** [comment]
Fastest developer in the west.
